name: Allegro Lokalnie Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      - name: Commit updated state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add state.json

          if git diff --cached --quiet; then
            echo "Brak zmian."
          else
            git commit -m "Update state.json"
            git push
          fi
